---
- name: Load variables to identify OS
  import_role:
    name: jm1.common # If Ansible raises "ERROR! the role 'jm1.common' was not found" then you might use the
                     # ansible-galaxy and the provided requirements.yml to install all missing role dependencies.

- name: Basic system setup
  import_role:
    name: jm1.base_system # If Ansible raises "ERROR! the role 'jm1.base_system' was not found" then you might use the
                          # ansible-galaxy and the provided requirements.yml to install all missing role dependencies.

- name: Install dependencies of collection jm1.pkg
  import_role:
    name: jm1.pkg.setup # If Ansible raises "ERROR! the role 'jm1.pkg.setup' was not found" then you might use the
                        # ansible-galaxy and the provided requirements.yml to install all missing role dependencies.

- name: Load tasks specific to OS
  include_tasks: "setup-{{ distribution_id|join('-') }}.yml"
  when: distribution_id|first == 'Debian' and
        distribution_id|last in ['10', '11', 'NA', 'Testing', 'Unstable']
