---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 # 1 day

- jm1.pkg.meta_pkg:
    name: "jm1-dev-haskell"
    version: "1"
    depends:
    - haskell-platform

    # TODO: re-add package ghc-mod as soon as it supports GHC 8.2.1+
    # Ref.: https://github.com/DanielG/ghc-mod/issues/900
