---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 # 1 day

# NOTE:
# - in Debian Stretch and later libpolarssl-dev has been renamed to libmbedtls-dev
# - list of packages that will be build by kdesrc-build: libkomparediff2-dev libgrantlee-dev
# - python-docutils is for rst2html command used by kdevelop for (better) documentation display
# - Debian Stretch packages libcv-dev, libcvaux-dev and libhighgui-dev have been replaced by libopencv-dev in Debian Sid
# - transitional package plasma-framework-dev (depends on libkf5plasma-dev) has been removed from sid
# - libkf5kface-dev depends on libkf5kface10.0.0 which in sid is build against old opencv packages that 
#   have already been removed from repository. Thus instead of depending on "libkf5.*-dev" we ignore
#   libkf5kface-dev by use of a posix regular expression.
# - libnm-glib-dev, libnm-glib-vpn-dev and libnm-util-dev are deprecated since network-manager 1.12.0-4

- jm1.pkg.meta_pkg:
    name: "jm1-kdevelop-common"
    version: "1"
    depends:
    # qt4
    #- qt4-demos
    #- qt4-designer
    - qt4-dev-tools
    #- qt4-doc
    - qt4-qmake
    - qt4-qmlviewer
    #- qt4-qtconfig
    #- libqt4-dev
    #
    #
    #
    # qt5
    - qt5-qmake
    #- qt5-doc
    - qtcreator
    # aptitude search '^libqt5.*-dev$' -F "%p"
    - libqt5charts5-dev
    - libqt5datavisualization5-dev
    - libqt5gamepad5-dev
    - libqt5gstreamer-dev
    - libqt5networkauth5-dev
    - libqt5opengl5-desktop-dev
    - libqt5opengl5-dev
    - libqt5pas-dev
    - libqt5scintilla2-dev
    - libqt5sensors5-dev
    - libqt5serialbus5-dev
    - libqt5serialport5-dev
    - libqt5svg5-dev
    - libqt5texttospeech5-dev
    - libqt5waylandclient5-dev
    - libqt5waylandcompositor5-dev
    - libqt5webchannel5-dev
    - libqt5webkit5-dev
    - libqt5websockets5-dev
    - libqt5webview5-dev
    - libqt5x11extras5-dev
    - libqt5xdg-dev
    - libqt5xdgiconloader-dev
    - libqt5xmlpatterns5-dev
    # aptitude search '^qt.*5-dev$' -F "%p"
    - qt3d5-dev
    - qtbase5-dev
    - qtconnectivity5-dev
    - qtdeclarative5-dev
    - qtlocation5-dev
    - qtmultimedia5-dev
    - qtpositioning5-dev
    - qtquickcontrols2-5-dev
    - qtscript5-dev
    - qttools5-dev
    - qtwebengine5-dev
    # aptitude search '^qt.*5-private-dev$' -F "%p"
    - qtbase5-private-dev
    - qtdeclarative5-private-dev
    - qttools5-private-dev
    - qtwebengine5-private-dev
    # aptitude search '^qt.*5-dev-tools$' -F "%p"
    - qt3d5-dev-tools
    - qtbase5-dev-tools
    - qtdeclarative5-dev-tools
    - qttools5-dev-tools
    - qtwayland5-dev-tools
    - qtwebengine5-dev-tools
    - qtxmlpatterns5-dev-tools
    # aptitude search '^python[0-9]?-pyqt5.[a-zA-Z0-9]*$' -F "%p"
    - python-pyqt5.qsci
    - python-pyqt5.qtmultimedia
    - python-pyqt5.qtopengl
    - python-pyqt5.qtpositioning
    - python-pyqt5.qtquick
    - python-pyqt5.qtsensors
    - python-pyqt5.qtserialport
    - python-pyqt5.qtsql
    - python-pyqt5.qtsvg
    - python-pyqt5.qtwebchannel
    - python-pyqt5.qtwebengine
    - python-pyqt5.qtwebkit
    - python-pyqt5.qtwebsockets
    - python-pyqt5.qtx11extras
    - python-pyqt5.qtxmlpatterns
    - python3-pyqt5.qsci
    - python3-pyqt5.qtchart
    - python3-pyqt5.qtmultimedia
    - python3-pyqt5.qtopengl
    - python3-pyqt5.qtpositioning
    - python3-pyqt5.qtquick
    - python3-pyqt5.qtsensors
    - python3-pyqt5.qtserialport
    - python3-pyqt5.qtsql
    - python3-pyqt5.qtsvg
    - python3-pyqt5.qtwebchannel
    - python3-pyqt5.qtwebengine
    - python3-pyqt5.qtwebkit
    - python3-pyqt5.qtwebsockets
    - python3-pyqt5.qtx11extras
    - python3-pyqt5.qtxmlpatterns
    - python3-pyqt5.qwt
    #
    - pyqt5-dev
    - pyqt5-dev-tools
    # aptitude search '^qt.*5-examples$' -F "%p"
    - qt3d5-examples
    - qtbase5-examples
    - qtcharts5-examples
    - qtconnectivity5-examples
    - qtdatavisualization5-examples
    - qtdeclarative5-examples
    - qtgamepad5-examples
    - qtlocation5-examples
    - qtmultimedia5-examples
    - qtnetworkauth5-examples
    - qtquickcontrols2-5-examples
    - qtquickcontrols5-examples
    - qtscript5-examples
    - qtsensors5-examples
    - qtserialbus5-examples
    - qtspeech5-examples
    - qtsvg5-examples
    - qttools5-examples
    - qtvirtualkeyboard5-examples
    - qtwayland5-examples
    - qtwebchannel5-examples
    - qtwebengine5-examples
    - qtwebsockets5-examples
    - qtwebview5-examples
    - qtxmlpatterns5-examples
    #
    - qt5-image-formats-plugins
    - qml
    #
    #
    #
    # kde
    - konsole-kpart
    - okteta
    - breeze-icon-theme
    - breeze
    - oxygen-icon-theme
    - plasma-integration
    - konsole
    - kate
    - dolphin
    - systemsettings
    - plasma-framework
    - plasma-sdk
    - plasma-workspace-wayland
    - python-docutils
    - kde-l10n-de
    - kde-sc-dev-latest
    #
    #
    #
    # misc
    - bison
    - flex
    - mesa-utils
    - heaptrack
    - heaptrack-gui

- when: not install_from_source
  block:
  - jm1.pkg.meta_pkg:
      name: "jm1-kdevelop"
      version: "1"
      depends:
      - jm1-kdevelop-common
      - kdevelop
      - clazy
      - kdevelop-php
      - kdevelop-python
      - plasma-kdevelop

- when: install_from_source
  block:
  - copy:
      src: "{{ distribution_id|join('-') }}/"
      dest: /
      mode: preserve

  - template:
      src: "{{ distribution_id|join('-') }}/usr/local/src/kdesrc/.kdesrc-buildrc.j2"
      dest: /usr/local/src/kdesrc/.kdesrc-buildrc

  - file:
      path: /usr/local/src/kdesrc/
      owner: nobody
      state: directory
      mode: "a+rx"
      recurse: yes

  - jm1.pkg.meta_pkg:
      name: "jm1-kdevelop-build-deps"
      version: "1"
      depends:
      - jm1-kdevelop-common
      - libkchart-dev
      - libdwarf-dev
      - libsparsehash-dev
      - libzstd-dev
      - libbz2-dev
      - libxslt-dev
      - libxml2-dev
      - libgif-dev
      - libvlc-dev
      - libvlccore-dev
      - libxapian-dev
      - fontforge
      - libgcrypt20-dev
      - libattr1-dev
      - network-manager-dev
      - libgtk-3-dev
      - xsltproc
      - xserver-xorg-dev
      - xserver-xorg-input-synaptics-dev
      - libpwquality-dev
      - modemmanager-dev
      - libxcb-keysyms1-dev
      - libepoxy-dev
      - libpolkit-agent-1-dev
      - libegl1-mesa-dev
      - libxcb-xkb-dev
      - libwww-perl
      - libxml-parser-perl
      - libjson-perl
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libarchive-dev
      - liblmdb-dev
      - libsvn-dev
      - libnm-dev
      #- 'libkf5([^k]+|(k([^f]|$)|kf([^a]|$)|kfa([^c]|$)|kfac([^e]|$)))+.*dev'
      - 'libkf5.*dev'
      - plasma-workspace-dev
      - okteta-dev
      - kdoctools-dev
      - libgrantlee5-dev
      - libkomparediff2-dev

  - name: Build KDevelop from source
    shell: /usr/local/bin/make_install_kdevelop.sh
    environment:
      HOME: /usr/local/src/kdesrc/
    register: install_result
    changed_when:
      not (install_result.rc == 124 and install_result.stderr == "KDevelop is already installed. Skipping..")
    failed_when:
      not (
        (install_result.rc == 0) or
        (install_result.rc == 124 and install_result.stderr == "KDevelop is already installed. Skipping..")
      )

- set_fact:
    install_result: !!null
