---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 # 1 day

- jm1.pkg.meta_pkg:
    name: "jm1-dev-openwrt"
    version: "1"
    depends:
    # OpenWrt / LEDE
    # Using the Image Generator (Image Builder)
    # Ref.: https://openwrt.org/docs/guide-user/additional-software/imagebuilder
    - subversion
    - build-essential
    - libncurses5-dev
    - zlib1g-dev
    - gawk
    - git
    - ccache
    - gettext
    - libssl-dev
    - xsltproc
    - wget
    - unzip
    - python
