---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 # 1 day

- name: Fetch CA certificates for LLVM's apt repository
  apt:
    name: 'ca-certificates'

- name: Copy apt sources for  LLVM Debian/Ubuntu nightly packages etc.
  copy:
    src: "{{ distribution_id|join('-') }}/"
    dest: /
    mode: preserve
  register: copy

- name: Update apt cache
  when: copy.changed
  # Handlers cannot be used here because in case that a role is run conditionally (when:) from a playbook then handlers
  # cannot be flushed here with 'meta: flush_handlers' because of Ansible issue #41313.
  # Ref.: https://github.com/ansible/ansible/issues/41313
  apt:
    update_cache: yes

- jm1.pkg.meta_pkg:
    name: "jm1-dev-cpp"
    version: "2"
    depends:
    # shell
    - bash
    - fzf
    # gcc
    - gcc
    - g++
    - gdb
    - gcc-7
    - g++-7
    - gcc-8
    - g++-8
    # clang
    - clang
    - llvm
    - lldb
    - libclang-dev
    - clang-tools-14
    - clang-tidy
    # vcs
    - bzr
    - mercurial
    - git
    - subversion
    - myrepos
    # editors
    - vim-nox
    - emacs-nox
    # tools
    - ccache
    - clangd
    - ninja-build
    - cloc
    - cppcheck
    - indent
    - indent-doc
    - doxygen
    - cmake
    - cmake-qt-gui
    - extra-cmake-modules
    - libgoogle-perftools-dev
    - google-perftools
    - nasm
    - valgrind
    - delta
    - c++-annotations-pdf
    - intltool
    - icu-devtools
    - bison
    - flex
    - catch
    - shellcheck
    - rr
    # packaging
    - quilt
    - packaging-dev
    # core libraries
    - libc++-dev
    - libomp-14-dev # OpenMP
    - mpi-default-dev
    - libboost-all-dev
    - libboost-doc
    # security libraries
    - libcrypto++-dev
    - libmbedtls-dev
    - libssl-dev
    - libssl-doc
    # computer vision libraries
    - libopencv-highgui-dev
    - libopencv-dev
    # misc libraries
    - freeglut3-dev
    - libusb-1.0-0-dev
    - libusb-1.0-doc
    - libxml2-dev

    # ubuntu-dev-tools requires entries in ppa-ubuntu-toolchain-r.list to be uncommented
    #
    # lldb* packages version-depend on python-lldb-* packages (e.g. lldb-6.0 => python-lldb-6.0),
    #  but python-lldb-* packages conflict with each other (python-lldb-6.0 != python-lldb-4.0).
    #  So only one lldb* package version can be installed at a time. lldb depends e.g. on lldb-4.0 which
    #  because of python-lldb-* conflicts with lldb-6.0, so either install lldb or lldb-6.0.
