galaxy_info:
  role_name: kdevelop
  author: Jakob Meng
  description: Build KDevelop from Git
  company: Hochschule Bonn-Rhein-Sieg
  license: license (GPLv3)

  min_ansible_version: 2.9

  platforms:
  # Ref.: https://galaxy.ansible.com/api/v1/platforms/
  - name: Debian
    versions:
    - bullseye

  galaxy_tags:
  - development
  - system

dependencies: []
